---
- hosts: all
  become: true
  become_user: root
  roles:
    - common
- hosts: head
  become: true
  become_user: root
  roles:
    - nfsserver
- hosts: comp*
  become: true
  become_user: root
  roles:
    - slurmd
